### PR TITLE
Fix compilation on macOS 10.13 for CsCore

### PR DESCRIPTION
**Pull request by rwols**
Close: https://github.com/copperspice/copperspice/issues/65
See also: https://bugreports.qt.io/browse/QTBUG-62266

### CODE REVIEW

**Comment by agserm** [comment]
Just for reference, due to LGPL licence incompatibilities, we cannot accept changes or pull requests based on any work contributed to the Qt Project after the release of 5.7.

Are you still getting an error using the current cs-1.4 from git? It does compile cleanly on our new 10.13 build server.

**Comment by rwols** [comment]
> we cannot accept changes or pull requests based on any work contributed to the Qt Project after the release of 5.7.

That's a bummer.

> Are you still getting an error using the current cs-1.4 from git? It does compile cleanly on our new 10.13 build server.

If you mean 63ff16ed486b26314c6d0220bee04fd63d7a4522 , then yes:

```
../../src/gui/kernel/qt_cocoa_helpers_mac.mm:262:38: error: use of undeclared identifier 'InvalidContext'
   require_action(inContext != NULL, InvalidContext, err = paramErr);
                                     ^
../../src/gui/kernel/qt_cocoa_helpers_mac.mm:263:37: error: use of undeclared identifier 'InvalidBounds'
   require_action(inBounds != NULL, InvalidBounds, err = paramErr);
                                    ^
../../src/gui/kernel/qt_cocoa_helpers_mac.mm:264:36: error: use of undeclared identifier 'InvalidImage'
   require_action(inImage != NULL, InvalidImage, err = paramErr);
                                   ^
```

Compiler is:
```
~/d/c/b/debug (cs-1.4 ☡=) /usr/local/bin/clang -v
clang version 7.0.0 (trunk 321933)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /usr/local/bin
```

**Comment by agserm** [comment]
> That's a bummer.

Yes, it is. It's unfortunate that with the 5.7 release they switched to LGPL 3 which is incompatible with the LGPL 2.1 of CopperSpice.

> If you mean 63ff16e , then yes:

How interesting. I assumed that the newer 10.13 SDK would only be an issue on a newer version of XCode but you are clearly using an older version. We'll need to find something else to test in order to determine when to use that error handling code.

**Comment by rwols** [comment]
So as it turns out, it seems to be an issue with me using clang-7.0 (that's the "LLVM" clang, NOT the "Apple" clang).

When compiling with AppleClang:

```
~/d/c/b/debug (cs-1.4 ☡=) c++ --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
at least CsCore, CsGui and CsXml compile. I haven't tried the rest.

**Pull request closed without merging**
