### PR TITLE
Issue #279: Improve css parsing performance

### PR DESCRIPTION
**Pull request by hs-apotell**
Issue #279: Improve css parsing performance

Replace use of indexing with iterators and a few other changes to improve css parsing performance.

### CODE REVIEW

**Comment by agserm** [comment]
Thanks so much for this PR. Can you give us a copy of the stylesheet you are using so we can run some benchmarks in our testing process?

**Comment by agserm** [comment]
There are a large number of lines removed in src/svg/qsvghandler.cpp, can you explain why they were removed? Were these changes based on your original ideas or from some other source? Was any functionality removed as part of this change?

**Comment by bgeller** [comment]
Can you provide a brief overview of what the code you removed in src/svg/qsvghandler.cpp was doing to help us understand it. Was the "25x performance gain" because of this change or moving from an index to iterators? 

I have a strong feeling your reasoning is pretty sound and accurate. Thanks for helping us learn more about this code.

**Comment by agserm** [comment]
We found some problems with these changes, and we are tracing it down.

**Comment by bgeller** [comment]
There was an issue in one of the methods where you initialized an iterator to input.end() and the token was -1. The iterator needed to be an std::optional. We added a branch, pulled in your PR, made this change, and then cleaned up some of the surrounding code for improved readability.  

You did some wonderful work and saved us a lot of time.  The push should happen by the end of the week.

Barbara

**Pull request merged**
