### PR TITLE
Fix for installing .cmake files in wrong location on Windows

### PR DESCRIPTION
**Pull request by velvet-jones**
This change installs CMake config files in CMAKE_PREFIX_PATH/lib, which seems to be where everyone else installs them.

### CODE REVIEW

**Comment by bgeller** [comment]
Please submit the export change as a separate PR so we can take this one.

**Comment by velvet-jones** [comment]
I will try to re-order these commits to get the export issue first and give you a pull request on just that one. For the others, however:

Yes there is no standard but there are de-facto standards and most everyone seems to be doing it one way while CopperSpice does it another way. Surely this is not what you intended when you initially forked Qt - to create a proprietary configuration with open source software and then not change it when presented with a better (correct, in fact) alternative.

CMAKE_PREFIX_PATH=c:\cs_lib\cmake\CopperSpice

Although it's possible to make this envar a list of directories, should that really be required? What if there are a hundred dependent libraries? Luckily today dependent libraries place their Config files in a de-facto standard directory structure and they can all be located when required - all except CopperSpice, which now requires its own entry in this envar. I should never have to specify the CopperSpice directory specifically in any invocation of cmake on my software.

I am aware that CopperSpice is open source and I can maintain my own fixes for this, but your reasoning sounds like "because we have always done it that way". Have you tested my changes? Do you know for certain that they don't work? Do you know for certain that your user base would rather you stick with the current configuration than do what everyone else is doing?

Are you really comfortable defying the likes of boost, openssl, zlib.... all these other projects that use the same configuration I have created this pull request for?

I have been very impressed by the amount of work put into your Qt fork and by the addition of a CMake build process, and I was looking forward to jumping in to provide a little help to polish it. But if I do the work, then provide a sound argument for it, only to be met with "we cannot make changes", then I wonder what this fork is really for.

**Comment by bgeller** [comment]
Just for completeness, the CopperSpice project is not the only CMake project which is set up this way. We understand this may be the first time you have encountered this layout and we value this discussion. By definition, our configuration is not "proprietary" since anyone is free to change it. 

Ironically, we have had other developers offer something completely different than what you have suggested. It is true that your set up is different than ours and we did consider it many years ago, but that does not make your ideas more correct or even incorrect. 

The Boost project has been through major upheaval and heartache in the last ten years as some members of  their steering committee push for a mandate of CMake. Sadly, this had never happened. Each library is still free to use what they want. If you look at their main page they talk about B2 which is a build system they created. Boost does not have a standard CMake layout.

Barbara

**Comment by bgeller** [comment]
>I was looking forward to jumping in to provide a little help to polish it. 

There are a lot of areas of CS which need more than just a polish and we hope you make many suggestions and pull requests. If you are looking for an area where you can help out, we suggest adding more Catch tests in Core and Network.  


>. . . then provide a sound argument for it, only to be met with "we cannot make changes", then I wonder what this fork is really for.

CS is derivative work however our project has gone in a very different direction from the original project. This is exactly what an open source project is meant to be. We want other developers to work with us and make suggestions. Some of these ideas will make it into CS and others will not become part of the project for a variety of different reasons.  

We hope you continue to submit your ideas and banter with us about things you find of value.

Barbara

**Comment by velvet-jones** [comment]
I appreciate the response. I will be out for a week and unable to continue during that time. That said:

- The Boost build system does not use cmake but they DO provide cmake config files for locating boost and they install those config files in the same location as zlib, openssl, et. al do.

The CMake documentation itself says:

https://cmake.org/cmake/help/v3.22/guide/using-dependencies/index.html

"The config files can usually be found in a directory whose name matches the pattern lib/cmake/<PackageName>, though they may be in other locations instead."

I have not proposed that you cannot put the config files somewhere else, only that the de-facto standard is to place them in lib/cmake, which is what this documentation implies to me. The fact that I can locate all of my libraries without specifying each individually indicates to me that this placement is in fact the de-facto standard layout, not just something I wish projects would do.

I stand by my statement that I think your layout is incorrect insofar as it is not the *expected* layout because your library cannot be found after "cmake --install" when I point the CMAKE_INSTALL_PREFIX to the local top-level install directory.

I have not yet fully converted your CMake build configuration to this de-facto standard because I am having trouble finding the release build, and I suspect that it has to do with VERSION matching. I will continue to look at this later. When I complete this, I encourage you to test your builds using my configuration.

- Bud

**Comment by bgeller** [comment]
>your library cannot be found after "cmake --install" when I point the CMAKE_INSTALL_PREFIX to the local top-level install directory.

With every software project you need to follow their current documentation. Our **CS Overview** docs explain exactly what you need to pass for the prefix. When you do, everything works. 

As you quoted, even the CMake docs state very clearly there is **no** set path nor is there a standard location for files. That means there is no "de-facto standard" but we understand you have preference and we respect your opinion. 

We may not be using the path you want, however the install process is documented and CS downstream projects build successfully.

Barbara

**Pull request closed without merging**
