### PR TITLE
Add color diagnostics when compiling with Ninja+Clang+CMake.

### PR DESCRIPTION
**Pull request by ahmedcharles**

### CODE REVIEW

**Comment by fluxer** [comment]
Question, why limit this to Ninja and Clang?

As a side note, recent versions of GCC and Clang do colorise their output by default and unless I misunderstand the purpose of `-fcolor-diagnostics` it is not needed at all. One can set GCC_COLORS and whatever the Clang alternative is or just change the build flags that CMake will use from their IDE/the CMake GUI.

**Comment by ahmedcharles** [comment]
Ninja buffers compiler output and clang only turns on colors when it detects a tty and cmake is the only build system that supports ninja, hence why it's only this combination of compilers. I don't use GCC so, I don't know if it has colors or not in this scenario. I don't see why not using GCC would block a clang only commit either.

**Comment by fluxer** [comment]
I did not intend to block the commit in any way. All of my attempts to build a project on Windows with Ninja and Clang have failed and I cannot tell how Ninja handles Clang on Windows (but I'm not very interested to find out either).

Cheers!

**Comment by ahmedcharles** [comment]
Oh, this is for Mac.

**Comment by agserm** [comment]
Closing this pull request since I have recently tested and discovered that this change causes problems for CI builds, or any time the build is done without being connected to a normal interactive terminal.

**Pull request closed without merging**
