### PR TITLE
Add intersects function to QPolygon and QPolygonF

### PR DESCRIPTION
**Pull request by cherichy**
When I port my code form Qt5 to copperspice, I found this function is missing.
So I added the intersects function to QPolygon and QPolygonF.

### CODE REVIEW

**Comment by bgeller** [comment]
Can you verify this is original work or that is is not based on Qt 5.7 or later ( which is LGPL 3 ).

**Comment by cherichy** [comment]
> Can you verify this is original work or that is is not based on Qt 5.7 or later ( which is LGPL 3 ).

Yes, I just use the intersects function from the QPainterPath class. This implementation is very simple.

**Comment by bgeller** [comment]
Sorry to be picky. Please know we want to take every single PR as this makes CS a better library.  

a) If this is original work then awesome.  

b) If you derived this from Qt, we just need to know the exact version.

Thank you and please keep submitting changes!

**Comment by cherichy** [comment]
I write this function in my own project when Qt was still at 5.3. But the intersects fucntion was provided later in Qt 5.10. So I think this PR is original though the implementation is the same (via the intersects function in QPainterPath).

**Comment by bgeller** [comment]
Thanks for letting us know this is your code. Just so you know why we asked, it is not possible for us to accept any code from Qt 5.7 or later. In fact, we suggest our contributors do not even look at their source beyond this point.  

Thanks so much and we will merge in the next week.

**Comment by agserm** [comment]
This PR has been committed as 7904105. Thank you for your contribution!

**Pull request closed without merging**
